### PR TITLE
updated README.md

### PR DESCRIPTION
**Pull request by abhinavsp0730**

### CODE REVIEW

**Comment by championballer** [comment]
Does not contribute substantially to the project.

**Comment by abhinavsp0730** [comment]
First of all you didn't clearly mentioned what to update in redme.md file.
And you tag it with hacktober label and good first issue. So it's obvious
that a beginner will create a pull request like me.
And now thanks to you i've completed 4 pr's now it only counts three and
I've to wait for more 7 days.
Don't tag unnecessary label to your project.
Go and learn what to tag or what to not.

**Comment by championballer** [comment]
First of all, I am sorry you feel that way. Also, google colab has no
relation to the project here. It's a machine learning related project where
algorithms are implemented and good first projects uploaded.

Second, the issue is created as the first reference point for an issue and
should be discussed at, before starting to work on something. Some issue
might not even suit you.

Third, for us open source contributions don't start and end with
Hacktoberfest, and hence don't mind me ignoring your unsubstantiated and
undiscussed PR. You can open another PR post discussion, which will
hopefully be accepted.

Hopeful that the tone of open source will be maintained in the future.

Goodluck.

**Comment by abhinavsp0730** [comment]
Instead of closing the PR you can ask for changes. Isn't it.

**Comment by championballer** [comment]
We ask for changes on PR's which have something specific to change. When
the entire code does nothing to help the project, it is better to allow the
contributor to open a new PR, which is not a big effort after the required
changes on their fork are completed, while others' PRs don't get piled up.

Goodluck.

**Pull request closed without merging**
